export const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'];
export const CONDITIONS = ['1/10', '2/10', '3/10', '4/10', '5/10', '6/10', '7/10', '8/10', '9/10', '10/10'];
export const COUNTRIES = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua & Deps", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Rep", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Congo {Democratic Rep}", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland {Republic}", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea North", "Korea South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar, {Burma}", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "St Kitts & Nevis", "St Lucia", "Saint Vincent & the Grenadines", "Samoa", "San Marino", "Sao Tome & Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad & Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"]
export const LEAGUES = ['Angolan First Division',
'Argentine Primera División',
'Austria Regional League Central',
'Austria Regional League East',
'Austria Regional League West',
'Austrian First League',
'Austrian Football Bundesliga',
'Azerbaijan Premier League',
'Belarusian Premier League',
'Belgian Pro League',
'Belgian Second Division',
'Bulgarian A Group',
'Bulgarian B Football Group',
'Bundesliga',
'CONCACAF Champions League',
'CONCACAF Champions League',
'Campeonato Brasileiro Série A',
'Campeonato Brasileiro Série B',
'Chilean',
'Chilean Primera División',
'Chinese FA Cup',
'Chinese Super League',
'Columbian Categoría Primera A',
'Columbian Categoría Primera B',
'Confederation of African Football Champions League',
'Confederation of African Football Confederation Cup',
'Copa Argentina',
'Copa Sudamericana',
'Coppa Italia',
'Costa Rican Primera División',
'Croatian Prva HNL (I)',
'Czech 2. Liga',
'Czech Gambrinus Liga (I)',
'Danish 1st Division',
'Danish Superliga',
'Dutch Eerste Divisie (Jupiler League)',
'Dutch Eredivisie',
'Ecuadorian Serie A',
'England League Cup',
'English Community Shield',
'English Conference',
'English Football League Championship',
'English Football League One',
'English Football League Two',
'English Premier League',
'Estonia Meistriliiga',
'Finnish First Division',
'Finnish Premier League',
'French Championnat National',
'French League Cup',
'French Ligue 1',
'French Ligue 2',
'Georgian Premier League',
'German 2. Bundesliga',
'German 3. Liga',
'German Bundesliga',
'German Regional League North',
'German Regionalliga Northeast',
'German Regionalliga Südwest',
'German Regionalliga West',
'Honduran Professional National Football League',
'Hungarian Division I',
'Iran Pro League',
'Ireland First Division',
'Ireland Premier Division',
'Irish League',
'Israeli Premier League',
'Japanese League Division 1',
'Japanese League Division 2',
'Japanese League Division 3',
'K League Classic',
'Korean FA Cup',
'Latvian Higher League',
'League of Ireland Cup',
'League of Ireland Premier Division',
'Liga MX',
'Liga de Fútbol Profesional Boliviano',
'Lithuanian A League',
'Macedonian First League',
'Moldovan National Division',
'Montenegrin First League',
'North American Soccer League',
'Norwegian Adeccoligaen (II)',
'Norwegian Tippeligaen (I)',
'Paraguayan Primera División',
'Peruvian Primera División',
'Polish Ekstraklasa',
'Polish First League',
'Polish I liga',
'Portuguese Second Division',
'Portuguese Segunda Liga',
'Regionalliga Bayern (IV)',
'Romanian Liga I',
'Romanian Liga II',
'Russian Football Premier League',
'Russian National Football League',
'Salvadoran Primera División',
'Scottish Football League First Division',
'Scottish Football League Second Division',
'Scottish Football League Third Division',
'Scottish League Cup',
'Scottish Premier League',
'Serbian SuperLiga',
'Singapore League',
'Slovak Super Liga',
'Slovenian PrvaLiga',
"South Africa's MTN 8 Cup",
'South African Premier Division',
'Suruga Bank Championship',
'Swedish Allsvenskan (I)',
'Swedish Superettan (II)',
'Swiss Super League',
'Swiss Super League',
'Thai Premier League',
'Torneo Argentino A',
'Turkish Super Cup',
'UEFA Champions League',
'UEFA Europa League',
'UEFA Under 21 Championship',
'US Major League Soccer',
'US Open Cup',
'Ukrainian Premier League',
'V. League (Vietnam)',
'Venezuelan Primera División']